import { readFileSync, writeFileSync } from 'fs';

const css = readFileSync('/tmp/annotakit-compiled.css', 'utf-8');

const output = `// Auto-generated — do not edit. Regenerated by: npm run build:css
export const annotakitCSS = ${JSON.stringify(css)};
`;

writeFileSync(
	new URL('../src/lib/styles/generated-css.ts', import.meta.url),
	output
);

console.log(`Embedded ${css.length} bytes of compiled CSS`);
